### PR TITLE
Switched intrusive_adapter to use pointed brackets

### LINKED ISSUE #5: Make intrusive_adapter to accept pointy brackets
It is possible to make `intrusive_adaptor` to accept pointy brackets instead of square brackets by [incrementally munching token trees](https://danielkeep.github.io/tlborm/book/pat-incremental-tt-munchers.html) (I have done this in [this macro](https://github.com/sebcrozet/alga/blob/master/alga/src/macros.rs#L37) and in this [monstrosity](https://play.rust-lang.org/?gist=b10733894a51e3c0d9339694b96692c0) of a macro that has now been replaced by custom derive based [implementation](https://github.com/WaDelma/bob)).

I'll give it a try once my work ends :P

### PR DESCRIPTION
**Pull request by WaDelma**
Fixes #5.

### CODE REVIEW

**Comment by Amanieu** [comment]
Can you update the minimum Rust version in .travis.yml?

**Comment by WaDelma** [comment]
Oh. I didn't even think about testing with older rust versions... So you are okay with making it to work only in newer ones?

The problem seems to be with where clauses that don't contain anything. So I could also fix it by slightly complicating the macro...

**Comment by Amanieu** [comment]
I'm fine if it only works in newer versions (as long as it works on the latest stable). However you should still update .travis.yml to indicate what the minimum required Rust version is.

**Comment by WaDelma** [comment]
Okay. I updated it to 1.16.

**Comment by Amanieu** [comment]
Thanks!

**Pull request merged**
